language: cpp

matrix:
  include:
    - os: windows
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .

notifications:
  email:
    - tiphaine.laurent@epitech.eu
    - hugo1.martin@epitech.eu
