version: 2

jobs:
  unix:
    docker:
      - image: ubuntu:18.04

        environment:
          CXX: /usr/bin/g++-8
          CC: /usr/bin/gcc-8

    steps:
      - checkout

      - run:
          name: Install g++-8
          command: "apt-get update && apt-get install -y g++-8"

      - run:
          name: Installing CMAKE
          command: "apt-get update && apt-get install -y cmake"

      - run:
          name: Installing X11
          command: "apt-get update && apt-get install -y libx11-dev"

      - run:
          name: Installing Xrandr
          command: "apt-get update && apt-get install -y libxrandr-dev"

      - run:
          name: Installing OpenGL
          command: "apt-get update && apt-get install -y libgl1-mesa-dev"

      - run:
          name: Installing Openal
          command: "apt-get update && apt-get install -y libopenal-dev"

      - run:
          name: Installing Freetype
          command: "apt-get update && apt-get install -y libfreetype6-dev"

      - run:
          name: Installing Vorbis
          command: "apt-get update && apt-get install -y libvorbis-dev"

      - run:
          name: Creating build files
          command: "cmake -H. -Bbuild"

      - run:
          name: Creating game binary
          command: "cmake --build build --target Starfarm"

#  windows:
#    docker:
#      - image: microsoft/dotnet-framework:4.7.1
#
#    steps:
#      - checkout
#
#      - run:
#          name: "Set execution policy to accept script execution"
#          shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
#          command: "Set-ExecutionPolicy RemoteSigned"
#
#      - run:
#          name: "Download & Install build tools"
#          shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
#          command: "./build_windows.ps1"

workflows:
  version: 2
  builds:
    jobs:
      - unix
#      - windows
